### ISSUE TITLE
Program messages don’t honor terminal opacity

### ISSUE THREAD

**Issue by shoober420** [91861/wayst#15]
Certain programs, like ffmpeg for this example, output messages when the task is finalized. The messages do not honor the users opacity settings however. Is this intended by the programs or is this a bug?
![0B8A2E3A-8DB1-4C32-9082-0D1FA385FDE9](https://user-images.githubusercontent.com/5150898/86540513-0685d600-bed4-11ea-8fff-8123695c8ef9.jpeg)

**Comment by 91861** [comment]
It's hard to tell exactly what the problem is from the picture. Could you provide more information?

For example, run wayst with `--debug-pty` in another terminal, print the interpreter state (Ctrl+Shift+Enter) right before and after the problem occurs and provide both outputs with all pty messages in between. Also the expected screen state from another terminal would be useful.

> The users terminal opacity settings are also not honored.

ffmpeg prints warnings with a non-default background color making it fully opaque, this is working as intended.

**Comment by shoober420** [comment]
Ok awesome, just wanted to check. Thank you very much.
