### ISSUE TITLE
Certain font sizes ignore last bottom column

### ISSUE THREAD

**Issue by shoober420** [91861/wayst#29]
When changing the font size in terminal with the Ctrl+Shift+equals key, the last bottom column will be unused. I tested with cmus audio player.
![90A93A33-6F61-43EA-97CC-D4330AD8B34F](https://user-images.githubusercontent.com/5150898/87226984-9ceb4900-c365-11ea-98ec-4e9fa1b6dba5.jpeg)

**Comment by 91861** [comment]
It will draw only as many rows/columns as it can fully fit inside the window. In the picture the cursor is one or two pixels taller than the empty space below it.

It looks a bit strange, because most other terminal emulators either only allow resizing the window to certain sizes (multiples of line height and character width) or center the image, creating a smaller gap on both window borders. It should be easy to add something like this.

**Comment by shoober420** [comment]
In case it helps with debugging, font sizes 13, 20, 27, and 35 appear to make use the last column properly.
